spring.application.name=demo
spring.datasource.url=jdbc:mysql://localhost:3306/companydb
spring.datasource.username=root
spring.datasource.password=amol

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081